# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-24 17:26
from __future__ import unicode_literals

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.FileField(default='', upload_to=blog.models.get_upload_file_name),
            preserve_default=False,
        ),
    ]
